// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRGvsWIpA72VBDI4W76JgF1mbQt7scxOw',
    appId: '1:8699556000:web:5872646b3be23cf54659c5',
    messagingSenderId: '8699556000',
    projectId: 'sballando-df89d',
    authDomain: 'sballando-df89d.firebaseapp.com',
    storageBucket: 'sballando-df89d.firebasestorage.app',
    measurementId: 'G-VLE7DRKWYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLM3ymZ_rg-0bUGr1oIfeqmGH1v07Ak7s',
    appId: '1:8699556000:android:821a248e4a37d4c14659c5',
    messagingSenderId: '8699556000',
    projectId: 'sballando-df89d',
    storageBucket: 'sballando-df89d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1BMHi5v_Ro0wAl0V1yFZJ_BTNOi85YqA',
    appId: '1:8699556000:ios:acd70c3b68d2aa704659c5',
    messagingSenderId: '8699556000',
    projectId: 'sballando-df89d',
    storageBucket: 'sballando-df89d.firebasestorage.app',
    iosBundleId: 'it.sballando.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1BMHi5v_Ro0wAl0V1yFZJ_BTNOi85YqA',
    appId: '1:8699556000:ios:acd70c3b68d2aa704659c5',
    messagingSenderId: '8699556000',
    projectId: 'sballando-df89d',
    storageBucket: 'sballando-df89d.firebasestorage.app',
    iosBundleId: 'it.sballando.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRGvsWIpA72VBDI4W76JgF1mbQt7scxOw',
    appId: '1:8699556000:web:a57512b7aaf2e90b4659c5',
    messagingSenderId: '8699556000',
    projectId: 'sballando-df89d',
    authDomain: 'sballando-df89d.firebaseapp.com',
    storageBucket: 'sballando-df89d.firebasestorage.app',
    measurementId: 'G-PPEQW2DD7M',
  );
}
